export default {
  STATUS_BAR_SET_COLOR: "[WHITE] STATUS_BAR_SET_COLOR",
  STATUS_BAR_CLOSE: "[WHITE] STATUS_BAR_CLOSE",
  STATUS_BAR_OPEN: "[WHITE] STATUS_BAR_OPEN",
  STATUS_BAR_TOGGLE: "[WHITE] STATUS_BAR_TOGGLE",
};
